sudo: false
language: node_js
node_js:
- node
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
arch:
- amd64
# - arm64
os:
- osx
# - linux
osx_image: xcode12.1
before_deploy:
- ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
- npm run prebuild
- hexdump "$TRAVIS_BUILD_DIR/prebuilds/darwin-x64/node.abi83.node" | head -10
- tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds"
  .
deploy:
  provider: releases
  draft: false
  prerelease: true
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
  # tags: true
    node: node
  api_key:  '$GITHUB_API_KEY'
